'use client';
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import * as Styles from "@mui/material/styles";

var make = Styles.styled("div")(function (param) {
      return {
              background: param.theme.palette.background.main,
              height: "100vh"
            };
    });

var Wrapper = {
  make: make
};

function HomePage(props) {
  return JsxRuntime.jsx(make, {
              children: "String"
            });
}

var make$1 = HomePage;

export {
  Wrapper ,
  make$1 as make,
}
/* make Not a pure module */
