'use client';
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "../../../../../../node_modules/.pnpm/rescript@11.0.0-rc.7/node_modules/rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";

function HomePage(props) {
  return JsxRuntime.jsx(JsxRuntime.Fragment, {
              children: Caml_option.some(JsxRuntime.jsx("div", {
                        children: "String"
                      }))
            });
}

var make = HomePage;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
