'use client';
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Font from "../../../shared/ui/tokens/Font.bs.js";
import * as Spacing$MuiSystem from "../../../../node_modules/@repo/rescript-mui-system/src/Spacing.bs.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as Styles from "@mui/material/styles";

var theme = Styles.createTheme({
      palette: {
        background: {
          main: "#F9F9FB"
        }
      },
      typography: {
        fontFamily: Font.inter.style.fontFamily
      },
      spacing: Spacing$MuiSystem.make
    });

function ThemeProvider(props) {
  return JsxRuntime.jsx(Styles.ThemeProvider, {
              children: props.children,
              theme: theme
            });
}

var make = ThemeProvider;

export {
  theme ,
  make ,
}
/* theme Not a pure module */
