// Generated by ReScript, PLEASE EDIT WITH CARE

import Middleware from "next-intl/middleware";

var middleware = Middleware({
      locales: [
        "ru",
        "en"
      ],
      defaultLocale: "ru",
      localePrefix: "never"
    });

export {
  middleware ,
}
/* middleware Not a pure module */
