'use client'
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Home from "../../../widgets/sidebar/ui/assets/svg/Home.res.js";
import * as NextIntl from "next-intl";
import * as Belt_Array from "../../../../../../node_modules/.pnpm/rescript@11.1.0-rc.1/node_modules/rescript/lib/es6/belt_Array.js";
import * as Caml_option from "../../../../../../node_modules/.pnpm/rescript@11.1.0-rc.1/node_modules/rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";
import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import ListItemIcon from "@mui/material/ListItemIcon";
import ListItemText from "@mui/material/ListItemText";
import ListItemButton from "@mui/material/ListItemButton";

function SidebarMenu(props) {
  var translate = NextIntl.useTranslations("SidebarMenu");
  var menuItems = [{
      key: "home",
      label: translate("home")
    }];
  return JsxRuntime.jsx(List, {
              children: Caml_option.some(Belt_Array.map(menuItems, (function (param) {
                          return JsxRuntime.jsx(ListItem, {
                                      children: Caml_option.some(JsxRuntime.jsxs(ListItemButton, {
                                                children: [
                                                  JsxRuntime.jsx(ListItemIcon, {
                                                        children: Caml_option.some(JsxRuntime.jsx(Home.make, {}))
                                                      }),
                                                  JsxRuntime.jsx(ListItemText, {
                                                        primary: Caml_option.some(param.label)
                                                      })
                                                ]
                                              }))
                                    }, param.key);
                        })))
            });
}

var make = SidebarMenu;

export {
  make ,
}
/* Home Not a pure module */
