'use client';
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Styles from "@mui/material/styles";

var make = Styles.styled("div")(function (param) {
      return {
              width: "200px",
              height: "100vh"
            };
    });

export {
  make ,
}
/* make Not a pure module */
