'use client';
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AppLogo from "./assets/svg/AppLogo.res.js";
import * as Caml_option from "../../../../../../node_modules/.pnpm/rescript@11.1.0-rc.1/node_modules/rescript/lib/es6/caml_option.js";
import * as SidebarMenu from "../../../entities/sidebar-menu/ui/SidebarMenu.res.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as Styles from "@mui/material/styles";

var make = Styles.styled("div")({
      height: "10%",
      display: "flex",
      justifyContent: "center",
      alignItems: "center"
    });

var LogoWrapper = {
  make: make
};

function Sidebar(props) {
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(make, {
                      children: Caml_option.some(JsxRuntime.jsx(AppLogo.make, {}))
                    }),
                JsxRuntime.jsx(SidebarMenu.make, {})
              ]
            });
}

var make$1 = Sidebar;

export {
  LogoWrapper ,
  make$1 as make,
}
/* make Not a pure module */
