// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "../../../../../../node_modules/.pnpm/rescript@11.1.0-rc.1/node_modules/rescript/lib/es6/caml_option.js";
import * as Server from "next-intl/server";

var config = Server.getRequestConfig(async function (param) {
      return {
              messages: Caml_option.some((await import("./messages/" + param.locale + ".json")).default)
            };
    });

export {
  config ,
}
/* config Not a pure module */
