// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Font from "../../../shared/ui/tokens/Font.res.js";
import * as Sidebar from "../../../widgets/sidebar/ui/Sidebar.res.js";
import * as SidebarLayout from "../../../shared/ui/layouts/sidebar-layout/SidebarLayout.res.js";
import * as ThemeProvider from "../../providers/theme/ThemeProvider.res.js";
import * as NextIntlProvider from "../../providers/next-intl/NextIntlProvider.res.js";
import * as JsxRuntime from "react/jsx-runtime";
import CssBaseline from "@mui/material/CssBaseline";

async function make(param) {
  var params = param.params;
  return JsxRuntime.jsx("html", {
              children: JsxRuntime.jsx("body", {
                    children: JsxRuntime.jsx(NextIntlProvider.make, {
                          children: JsxRuntime.jsxs(ThemeProvider.make, {
                                children: [
                                  JsxRuntime.jsx(CssBaseline, {}),
                                  JsxRuntime.jsx(SidebarLayout.make, {
                                        sidebar: JsxRuntime.jsx(Sidebar.make, {}),
                                        page: param.children
                                      })
                                ]
                              }),
                          lang: params.lang
                        }),
                    className: Font.inter.className
                  }),
              lang: params.lang
            });
}

var NextLayout = make;

var metadata = {
  title: "Music app",
  description: "Generated by create turbo"
};

var make$1 = NextLayout;

export {
  metadata ,
  make$1 as make,
}
/* Font Not a pure module */
