type metadata = {
  @optional
  title: string,
  @optional
  description: string,
}

let metadata: metadata = {
  title: "Music app",
  description: "Generated by create turbo",
}

@react.component
let make = (~children) => {
  <html lang="en">
    <body className={Font.inter.className}>
      <ThemeProvider>
        <Mui.CssBaseline />
        <SidebarLayout sidebar={<Sidebar />} page=children />
      </ThemeProvider>
    </body>
  </html>
}
