type metadata = {
  @optional
  title: string,
  @optional
  description: string,
}

let metadata: metadata = {
  title: "Music app",
  description: "Generated by create turbo",
}

type params = {lang: string}

@react.component
let make = async (~children, ~params) => {
  let {lang} = params

  <html lang=params.lang>
    <body className={Font.inter.className}>
      <NextIntlProvider lang>
        <ThemeProvider>
          <Mui.CssBaseline />
          <SidebarLayout sidebar={<Sidebar />} page=children />
        </ThemeProvider>
      </NextIntlProvider>
    </body>
  </html>
}
