// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Font from "../../../shared/ui/tokens/Font.bs.js";
import * as Sidebar from "../../../widgets/sidebar/ui/Sidebar.bs.js";
import * as SidebarLayout from "../../../shared/ui/layouts/sidebar-layout/SidebarLayout.bs.js";
import * as ThemeProvider from "../../providers/theme/ThemeProvider.bs.js";
import * as JsxRuntime from "react/jsx-runtime";
import CssBaseline from "@mui/material/CssBaseline";

function NextLayout(props) {
  return JsxRuntime.jsx("html", {
              children: JsxRuntime.jsx("body", {
                    children: JsxRuntime.jsxs(ThemeProvider.make, {
                          children: [
                            JsxRuntime.jsx(CssBaseline, {}),
                            JsxRuntime.jsx(SidebarLayout.make, {
                                  sidebar: JsxRuntime.jsx(Sidebar.make, {}),
                                  page: props.children
                                })
                          ]
                        }),
                    className: Font.inter.className
                  }),
              lang: "en"
            });
}

var metadata = {
  title: "Music app",
  description: "Generated by create turbo"
};

var make = NextLayout;

export {
  metadata ,
  make ,
}
/* Font Not a pure module */
