'use client';
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as NextIntl from "next-intl";
import * as Caml_option from "../../../../../../node_modules/.pnpm/rescript@11.1.0-rc.1/node_modules/rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as Styles from "@mui/material/styles";

var make = Styles.styled("div")(function (param) {
      return {
              background: param.theme.palette.background.main,
              height: "100vh"
            };
    });

var Wrapper = {
  make: make
};

function HomePage(props) {
  var translate = NextIntl.useTranslations("HomePage");
  return JsxRuntime.jsx(make, {
              children: Caml_option.some(translate("main"))
            });
}

var make$1 = HomePage;

export {
  Wrapper ,
  make$1 as make,
}
/* make Not a pure module */
