'use client';
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as System from "@mui/system";

var spacingFunction = System.createSpacing();

var spacingFunctionAllDirections = System.createSpacing();

var spacingFunctionVerticalHorisontal = System.createSpacing();

var spacingFunctionTopHorisontalBottom = System.createSpacing();

var spacingFunctionTopRightBottomLeft = System.createSpacing();

function make($$arguments) {
  if (typeof $$arguments !== "object") {
    return spacingFunction();
  }
  switch ($$arguments.TAG) {
    case "AllDirections" :
        return spacingFunctionAllDirections($$arguments._0);
    case "VerticalHorisontal" :
        return spacingFunctionVerticalHorisontal($$arguments._0, $$arguments._1);
    case "TopHorisontalBottom" :
        return spacingFunctionTopHorisontalBottom($$arguments._0, $$arguments._1, $$arguments._2);
    case "TopRightBottomLeft" :
        return spacingFunctionTopRightBottomLeft($$arguments._0, $$arguments._1, $$arguments._2, $$arguments._3);
    
  }
}

export {
  spacingFunction ,
  spacingFunctionAllDirections ,
  spacingFunctionVerticalHorisontal ,
  spacingFunctionTopHorisontalBottom ,
  spacingFunctionTopRightBottomLeft ,
  make ,
}
/* spacingFunction Not a pure module */
