// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "../../../../../../../node_modules/.pnpm/rescript@11.1.0-rc.1/node_modules/rescript/lib/es6/caml_option.js";
import Box from "@mui/material/Box";
import * as JsxRuntime from "react/jsx-runtime";
import Grid from "@mui/material/Grid";

function SidebarLayout(props) {
  return JsxRuntime.jsx(Box, {
              children: Caml_option.some(JsxRuntime.jsxs(Grid, {
                        children: [
                          JsxRuntime.jsx(Grid, {
                                xs: 3,
                                children: Caml_option.some(props.sidebar),
                                item: true
                              }),
                          JsxRuntime.jsx(Grid, {
                                xs: 9,
                                children: Caml_option.some(props.page),
                                item: true
                              })
                        ],
                        container: true
                      })),
              sx: {
                display: "flex",
                flexGrow: "1"
              }
            });
}

var make = SidebarLayout;

export {
  make ,
}
/* @mui/material/Box Not a pure module */
