// Generated by ReScript, PLEASE EDIT WITH CARE


var NextRequest = {};

var NextResponse = {};

var NextMiddleware = {};

export {
  NextRequest ,
  NextResponse ,
  NextMiddleware ,
}
/* No side effect */
