// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ThemeProvider from "../providers/theme/ThemeProvider.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function Layout(props) {
  return JsxRuntime.jsx("html", {
              children: JsxRuntime.jsx("body", {
                    children: JsxRuntime.jsxs(ThemeProvider.make, {
                          children: [
                            JsxRuntime.jsx("div", {
                                  children: "Aboba"
                                }),
                            props.children
                          ]
                        }),
                    className: props.className
                  }),
              lang: "en"
            });
}

var metadata = {
  title: "Music app",
  description: "Generated by create turbo"
};

var make = Layout;

export {
  metadata ,
  make ,
}
/* ThemeProvider Not a pure module */
