type metadata = {
  @optional
  title: string,
  @optional
  description: string,
}

let metadata: metadata = {
  title: "Music app",
  description: "Generated by create turbo",
}

@react.component
let make = (~children, ~className) => {
  <html lang="en">
    <body className>
      <ThemeProvider>
        <div> {"Aboba"->React.string} </div>
        children
      </ThemeProvider>
    </body>
  </html>
}
